Lesson2: homework
alina-krivolapova/learn_python pull request #1
Opened 2021-05-19 09:16 UTC by alina-krivolapova

2021-05-20 09:17 UTC, n05tr0m0 requested changes
Посмотрел, прокомментировал.

2021-05-20 09:17 UTC, n05tr0m0 commented on lesson2/school.py
> +    for score in school_class["scores"]:
Твоё решение корректное, но можно не использовать второй цикл, а решить задачу в один цикл.

Я бы упросил до такого:

```python

mid_score_sum = []

for each_class in scores_map:
    mid_score = sum(each_class['scores']) / len(each_class['scores'])
    mid_score_sum.append(mid_score)
    print(f'Средняя оценка класса {each_class["school_class"]} - {mid_score}')

mid_school_score = sum(mid_score_sum) / len(scores_map)
print(f'Средняя оценка по школе: {mid_school_score:.2f}')
```

2021-05-20 09:17 UTC, n05tr0m0 commented on lesson2/strings_comparison.py
> +    raise ValueError("Мы не нашли паттерн для сравнения, попробуй еще раз")
Для чего тут это возбуждение исключения ошибки?

2021-05-20 10:00 UTC, alina-krivolapova commented on lesson2/age.py
> +def tell_me_what_should_i_do(age: float) -> str:
я не очень это поняла из условия, по идее юзер может писать типа 6,5 (вряд ли, конечно, 6,2)

2021-05-20 10:04 UTC, n05tr0m0 commented on lesson2/age.py
> +def tell_me_what_should_i_do(age: float) -> str:
Так можно проверять на инт и всё, всё что кроме инта отсеивать или преобразовывать.

2021-05-20 10:07 UTC, alina-krivolapova commented on lesson2/dicounted_price.py
> +        print("Указана неверная цена или размер скидки.")
не очень согласна - у тебя будет в некоторых случаях будет возвращаться число (цена со скидкой), а в некоторых строка - можно накосячить при использовании функции, нужно будет делать проверку на вернувшийся тип
или я не поняла?

2021-05-20 10:07 UTC, alina-krivolapova commented on lesson2/dicounted_price.py
> +        raise ValueError('Слишком большая максимальная скидка')
это я списала из урока про функции:)

2021-05-20 10:11 UTC, alina-krivolapova commented on lesson2/strings_comparison.py
> +    raise ValueError("Мы не нашли паттерн для сравнения, попробуй еще раз")
можно делать что-то другое, в случае, если паттерн не нашли - можно вернуть 4, например
не знаю, что лучше, если честно

2021-05-20 10:11 UTC, n05tr0m0 commented on lesson2/dicounted_price.py
> +        print("Указана неверная цена или размер скидки.")
Ты не так поняла, если произошёл `except` то выполняется код ниже `except`, соответсвенно вернётся именно то, что ты написала, хоть 2 + 2, если так напишешь.

Если перехвата ошибки не произошло, код просто будет выполняясь дальше по твоему сценарию.

2021-05-20 10:12 UTC, n05tr0m0 commented on lesson2/dicounted_price.py
> +        raise ValueError('Слишком большая максимальная скидка')
Так это не критично в данном случае, но если бы писала это внутри большой программы, то возбуждать исключение было бы лишним, скорее нужно возвращать сообщение, что что-то не так

2021-05-20 10:16 UTC, alina-krivolapova commented on lesson2/age.py
> +        action = tell_me_what_should_i_do(user_age)
согласна, переделаю
но так почему-то написано в задании
https://learn.python.ru/lessons/10_if.html?full#19

2021-05-20 10:20 UTC, n05tr0m0 commented on lesson2/strings_comparison.py
> +    raise ValueError("Мы не нашли паттерн для сравнения, попробуй еще раз")
В условиях не сказано, что это нужно, зачем выполнять больше чем требуется?
Плюс ко всему, опять же, возбуждать исключение я бы не стал, а просто выдал сообщение в ответ.
У тебя райз будет исполняться всегда, за исключением тех моментов, когда условия попадают под if'ы

2021-05-20 10:22 UTC, alina-krivolapova commented on lesson2/dicounted_price.py
> +        print("Указана неверная цена или размер скидки.")
да, при исключении в моем случае выведется строка из принт и вернется None 
в твоем - вернется строка
то есть в моем случае я могла бы  сделать просто:
if discounted(arg1, arg2): 
         do_smth

2021-05-20 10:23 UTC, n05tr0m0 commented on lesson2/age.py
> +        action = tell_me_what_should_i_do(user_age)
Так ты ввод от пользователя положила в переменную.
Я про переменную `action`, она тут лишняя.

2021-05-20 10:24 UTC, n05tr0m0 commented on lesson2/age.py
> +        action = tell_me_what_should_i_do(user_age)
Да, точно, забыл, что в задании так написано.
Тогда всё верно.
Скорее всего это сделано для практики новичков.

2021-05-20 10:55 UTC, n05tr0m0 commented on lesson2/dicounted_price.py
> +        print("Указана неверная цена или размер скидки.")
На самом деле можно как угодно написать, в зависимости от условий. Это же программирование :)

Программист сам придумывает как написать, а вот хорошо ли или плохо он написал покажет практика выполнения кода.

2021-05-23 10:33 UTC, n05tr0m0 reviewed
Прокомментировал

2021-05-23 10:33 UTC, n05tr0m0 commented on lesson2/age.py
> +        print("Возраст введен невернло. Введите целое число.")
Так тоже норм, а тут просто у тебя опечатка в слове "неверно" :)

2021-05-23 10:33 UTC, n05tr0m0 commented on lesson2/strings_comparison.py
> +    if not isinstance(str1, str) or not isinstance(str2, str):
почему `or`?

2021-05-23 10:33 UTC, n05tr0m0 commented on lesson2/strings_comparison.py
> +    print("Мы не нашли паттерн для сравнения, попробуй еще раз")
В этом принте нет нужды :)

2021-05-23 10:33 UTC, n05tr0m0 commented on lesson2/talk_to_user.py
> +        print(answer_map[input("Введите вопрос: ").lower().split("?")[0]])
Для больше читаемости строчки, я бы разделил на 2 строки:
```python
user_input = input("Введите вопрос: ".lower().split("?")[0]
print(answer_map[user_input]
```

Так более читаемо, о том что происходит.

2021-05-26 10:49 UTC, n05tr0m0 reviewed
Тест

2021-05-26 16:15 UTC, alina-krivolapova commented on lesson2/strings_comparison.py
> +    if not isinstance(str1, str) or not isinstance(str2, str):
если хотя бы один из параметров не строка, значит мы должны вернуть 0
ну я так поняла это из задания
>> Проверить, является ли то, что передано функции, строками. Если нет - вернуть 0

2021-05-26 16:16 UTC, alina-krivolapova commented on lesson2/strings_comparison.py
> +    print("Мы не нашли паттерн для сравнения, попробуй еще раз")
ну лучше показать, что программа пыталась чет там делать:)
но согласна, что в целом это не обязательно

2021-05-28 08:47 UTC, n05tr0m0 reviewed
Прокомментировал

2021-05-28 08:47 UTC, n05tr0m0 commented on lesson2/strings_comparison.py
> +    if not isinstance(str1, str) or not isinstance(str2, str):
Почему хотя бы 1? :) Там написано строками :)

2021-05-28 08:47 UTC, n05tr0m0 commented on lesson2/talk_to_user.py
> +hello_user()
Забываешь добавлять:

```python
if __name__ == '__main__':
    hello_user()
    ask_user()
```

2021-05-29 01:17 UTC, n05tr0m0 approved these changes

2021-05-29 01:17 UTC, merged